server:
  port: 9999
  address: 127.0.0.1

#fpga:
#  workspace:
#    base: /tmp  # ?????
#
#spring:
#  web:
#    resources:
#      static-locations: classpath:/static/
#      add-mappings: true
logging:
  level:
    org.example: debug
